### ISSUE TITLE
Simplification and ease of use for projects that want to use metacall as a library

### ISSUE THREAD

**Issue by trgwii** [metacall/distributable-linux#15]
While attempting to embed metacall into a [zig application](https://github.com/metacall/zig-example), I encountered some confusion, and I suggest the following changes to the release tarball in order to ease the life of people trying to use it in their projects:

- [ ] Symlink `gnu/include` to `gnu/store/szllrsimcnm8r1iiampsikhnnpk3c4zd-metacall-0.6.2/include`
- [ ] Don't require `CONFIGURATION_PATH`
- [ ] Symlink `gnu/configurations` to `gnu/store/y1qviprznny30lmnkgyinh0a3bsf5r40-profile/configurations`
- [ ] Get `c-ares` and `icu4c` into `gnu/lib` somehow

**Comment by viferga** [comment]
All solved in the next version.
